### ISSUE TITLE
need help, thx!

### ISSUE THREAD

**Issue by 101142TS** [tracer0tong/de#1]
when i run this code, it says

Traceback (most recent call last):
  File "de.py", line 248, in <module>
    class DexDecompiler:
  File "de.py", line 259, in DexDecompiler
    PackedSwitchPayload = Struct('psp',Magic(b'\x00\x01'),
NameError: name 'Magic' is not defined

**Comment by tracer0tong** [comment]
Can you tell me version of 'construct' library that you're using?

**Comment by 101142TS** [comment]
fixed, thank you
